# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('postedTime', models.DateTimeField(auto_now_add=True)),
                ('originalPrice', models.CharField(blank=True, default='', max_length=10)),
                ('brandNew', models.NullBooleanField()),
                ('bargain', models.NullBooleanField()),
                ('exchange', models.NullBooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
