# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20160213_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycategory',
            name='icon',
            field=models.CharField(default='jfjf', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SecondaryCategory'),
        ),
    ]
