# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160214_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycategory',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
