# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_primarycategory_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarycategory',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Version'),
        ),
    ]
