# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160214_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gps',
            field=models.CharField(default='-1.266732 51.7585118', max_length=40),
            preserve_default=False,
        ),
    ]
