# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImageUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='product.Product')),
            ],
        ),
    ]
