# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_thumbnailimageuuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailimageuuid',
            name='product',
        ),
        migrations.DeleteModel(
            name='ThumbnailImageUUID',
        ),
    ]
