# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_citycountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cityCountry',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(default='\u725b\u6d25', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default='\u82f1\u56fd', max_length=10),
            preserve_default=False,
        ),
    ]
