# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160221_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainimage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
