# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20160302_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gps',
        ),
    ]
