# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20160318_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(default='default.png', max_length=50),
        ),
    ]
