# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 07:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20160318_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boughtProducts', to=settings.AUTH_USER_MODEL),
        ),
    ]
