# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarycategory',
            name='icon_naked',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
