# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='EMPass',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='EMUser',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
