# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20160323_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='introduction',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
