# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20160414_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orderer',
            field=models.ManyToManyField(related_name='orderedProducts', through='product.OrderMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
