# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_orderer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermembership',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
