# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20160422_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='product.OrderMembership'),
        ),
    ]
