# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20160422_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followermapping', to=settings.AUTH_USER_MODEL)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingmapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='follower',
            field=models.ManyToManyField(related_name='following', through='product.UserFollowMapping', to=settings.AUTH_USER_MODEL),
        ),
    ]
