# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 23:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20160505_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='time_ordered',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 24, 23, 34, 3, 874000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
