# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_feedback_time_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='time_ordered',
            new_name='time',
        ),
    ]
