# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easetoken',
            name='expires_in',
            field=models.DateTimeField(),
        ),
    ]
